export const treeData = {
  "msg":
      "success", "code":
      0, "response":
      {
        "roleName":
            "系统管理员", "name":
            "张博", "id":
            646, "Menu":
            [{"id": 6, "parentId": 623, "name": "质控员数据", "url": "", "remark": "菜单权限", "createTime": "2018-11-20T13:23:01.000+0800", "type": "menu", "delFlag": null}, {
              "id": 241,
              "parentId": 7,
              "name": "质控员报表",
              "url": null,
              "remark": "菜单权限",
              "createTime": "2019-01-15T10:06:35.000+0800",
              "type": "menu",
              "delFlag": null
            }, {
              "id": 253,
              "parentId": 241,
              "name": "登录日志导出",
              "url": "/statistics/reportCenter/exportQcLoginLogs",
              "remark": "接口权限",
              "createTime": "2019-01-18T11:11:29.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 242,
              "parentId": 241,
              "name": "登录日志",
              "url": "/statistics/reportCenter/qcLoginLogs",
              "remark": "接口权限",
              "createTime": "2019-01-15T10:07:03.000+0800",
              "type": "interface",
              "delFlag": null
            }, {"id": 5, "parentId": 623, "name": "通道数据", "url": "", "remark": "菜单权限", "createTime": "2018-11-20T13:23:01.000+0800", "type": "menu", "delFlag": null}, {
              "id": 7,
              "parentId": 623,
              "name": "报表中心",
              "url": "",
              "remark": "菜单权限",
              "createTime": "2018-11-20T13:23:01.000+0800",
              "type": "menu",
              "delFlag": null
            }, {
              "id": 188,
              "parentId": 202,
              "name": "通道搜索",
              "url": "/statistics/reportCenter/passageReportList",
              "remark": "接口权限",
              "createTime": "2018-12-27T09:50:08.000+0800",
              "type": "interface",
              "delFlag": null
            }, {"id": 201, "parentId": 7, "name": "安检员报表", "url": "", "remark": "菜单权限", "createTime": "2018-12-26T15:23:03.000+0800", "type": "menu", "delFlag": null}, {
              "id": 297,
              "parentId": 5,
              "name": "已安检行李数",
              "url": "/checkNumRecord/getCheckNowThunk",
              "remark": "接口权限",
              "createTime": "2019-02-18T10:17:00.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 296,
              "parentId": 5,
              "name": "当月周通过率",
              "url": "/checkNumRecord/getMonthlyPercentage",
              "remark": "接口权限",
              "createTime": "2019-02-18T10:16:16.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 295,
              "parentId": 5,
              "name": "已安检总人数",
              "url": "/checkNumRecord/getChecktotals",
              "remark": "接口权限",
              "createTime": "2019-02-18T10:15:24.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 294,
              "parentId": 5,
              "name": "今日安检人数",
              "url": "/checkNumRecord/getCheckTime",
              "remark": "接口权限",
              "createTime": "2019-02-18T10:14:19.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 298,
              "parentId": 6,
              "name": "通道复检状态列表",
              "url": "/recheckLog/findRecheckLogList",
              "remark": "接口权限",
              "createTime": "2019-02-18T16:07:50.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 301,
              "parentId": 333,
              "name": "导出复检日志",
              "url": null,
              "remark": "菜单权限",
              "createTime": "2019-02-18T20:51:56.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 302,
              "parentId": 301,
              "name": "导出复检日志接口",
              "url": "/recheckLog/exportRecheckLogExcel",
              "remark": "接口权限",
              "createTime": "2019-02-18T20:55:06.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 300,
              "parentId": 188,
              "name": "复检日志详细信息",
              "url": "/recheckLog/getRecheckInfo",
              "remark": "接口权限",
              "createTime": "2019-02-18T20:11:41.000+0800",
              "type": "4",
              "delFlag": null
            }, {"id": 309, "parentId": 11, "name": "导出模板", "url": null, "remark": "菜单权限", "createTime": "2019-02-21T14:32:22.000+0800", "type": "3", "delFlag": null}, {
              "id": 202,
              "parentId": 7,
              "name": "通道报表",
              "url": "",
              "remark": "菜单权限",
              "createTime": "2018-12-28T15:24:14.000+0800",
              "type": "menu",
              "delFlag": null
            }, {
              "id": 193,
              "parentId": 202,
              "name": "通道报表导出",
              "url": "/statistics/reportCenter/exportPassageReportList",
              "remark": "接口权限",
              "createTime": "2018-12-28T15:17:30.000+0800",
              "type": "interface",
              "delFlag": null
            }, {"id": 4, "parentId": 623, "name": "总体数据", "url": "", "remark": "菜单权限", "createTime": "2018-11-20T13:23:01.000+0800", "type": "menu", "delFlag": null}, {
              "id": 314,
              "parentId": 4,
              "name": "获取本月质控员登录情",
              "url": "/sloLog/getLoginMonthTrend",
              "remark": "接口权限",
              "createTime": "2019-02-22T14:44:42.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 313,
              "parentId": 4,
              "name": "获取本周质控员登录情",
              "url": "/sloLog/getLoginWeekTrend",
              "remark": "接口权限",
              "createTime": "2019-02-22T14:29:34.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 310,
              "parentId": 4,
              "name": "开包行李数",
              "url": "/checkNumRecord/getOverallOBanks",
              "remark": "接口权限",
              "createTime": "2019-02-22T14:20:13.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 308,
              "parentId": 4,
              "name": "当日质控员登录记录",
              "url": "/sloLog/getLoginLogRecord",
              "remark": "接口权限",
              "createTime": "2019-02-20T16:20:40.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 307,
              "parentId": 4,
              "name": "当日所有在线人员",
              "url": "/sloLog/getTodayOnEmp",
              "remark": "接口权限",
              "createTime": "2019-02-20T10:40:32.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 306,
              "parentId": 4,
              "name": "当日所有通道安检的总",
              "url": "/checkNumRecord/getOverallThunk",
              "remark": "接口权限",
              "createTime": "2019-02-19T09:39:36.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 305,
              "parentId": 4,
              "name": "当日通道安检的总人数",
              "url": "/checkNumRecord/getOverallPeploes",
              "remark": "接口权限",
              "createTime": "2019-02-19T09:32:59.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 304,
              "parentId": 4,
              "name": "当前开放通道",
              "url": "/checkNumRecord/getOverallData",
              "remark": "接口权限",
              "createTime": "2019-02-19T09:32:09.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 303,
              "parentId": 4,
              "name": "当日所有通",
              "url": "/checkNumRecord/getNumAvg",
              "remark": "接口权限",
              "createTime": "2019-02-19T09:31:26.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 337,
              "parentId": 4,
              "name": "总体到岗率",
              "url": "/checkNumRecord/getOverallDutyRate",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:12:50.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 336,
              "parentId": 4,
              "name": "部门迟到人数",
              "url": "/checkNumRecord/getOverallDebtLate",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:12:10.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 335,
              "parentId": 5,
              "name": "当天一个通道开包的行李占比数",
              "url": "/checkNumRecord/getOpenBanks",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:08:01.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 334,
              "parentId": 5,
              "name": "开包件数总趋势-当月当周每天百分比",
              "url": "/checkNumRecord/getOpenBankBfb",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:06:37.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 333,
              "parentId": 5,
              "name": "当日所有通道每小时安检速率",
              "url": "/checkNumRecord/getNumAvg",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:04:53.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 332,
              "parentId": 5,
              "name": "已安检速率",
              "url": "/checkNumRecord/getMonthlyPercentage",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:02:28.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 331,
              "parentId": 5,
              "name": "安检人数周趋势-已安检总人数",
              "url": "/checkNumRecord/getChecktotals",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:01:32.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 330,
              "parentId": 5,
              "name": "今日安检行李数",
              "url": "/checkNumRecord/getCheckNowThunk",
              "remark": "接口权限",
              "createTime": "2019-03-07T11:00:44.000+0800",
              "type": "4",
              "delFlag": null
            }, {
              "id": 329,
              "parentId": 5,
              "name": "今日安检人数,时间",
              "url": "checkNumRecord/getCheckTime",
              "remark": "接口权限",
              "createTime": "2019-03-07T10:55:56.000+0800",
              "type": "4",
              "delFlag": null
            }, {"id": 621, "parentId": 0, "name": "安检质控质控端", "url": null, "remark": null, "createTime": "2022-09-21T11:10:01.000+0800", "type": "0", "delFlag": null}, {
              "id": 629,
              "parentId": 621,
              "name": "修改密码",
              "url": "/sys/user/modifyPassword",
              "remark": "菜单权限",
              "createTime": "2022-09-21T14:14:55.000+0800",
              "type": "menu",
              "delFlag": null
            }, {"id": 625, "parentId": 621, "name": "安检回查", "url": null, "remark": "菜单权限", "createTime": "2022-09-21T13:37:41.000+0800", "type": "menu", "delFlag": null}, {
              "id": 658,
              "parentId": 625,
              "name": "重点人员过检记录",
              "url": "/extra/getImportantPass",
              "remark": "接口权限",
              "createTime": "2022-09-22T13:51:50.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 660,
              "parentId": 658,
              "name": "重点人员导出",
              "url": "/scb/extra/exportData",
              "remark": "接口权限",
              "createTime": "2022-09-22T13:53:30.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 659,
              "parentId": 658,
              "name": "重点人员过检记录查询",
              "url": "/scb/extra/getImportantPass",
              "remark": "接口权限",
              "createTime": "2022-09-22T13:53:02.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 657,
              "parentId": 625,
              "name": "信息过滤查询",
              "url": "/scb/callback/info",
              "remark": "接口权限",
              "createTime": "2022-09-22T13:50:42.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 656,
              "parentId": 625,
              "name": "安检追溯",
              "url": "/callback/nodeInfo",
              "remark": "接口权限",
              "createTime": "2022-09-22T13:49:46.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 628,
              "parentId": 625,
              "name": "货检回查",
              "url": "/securityCheck/goodsInspect",
              "remark": "菜单权限",
              "createTime": "2022-09-21T13:39:06.000+0800",
              "type": "menu",
              "delFlag": null
            }, {
              "id": 653,
              "parentId": 628,
              "name": " 货物详细信息",
              "url": "/waybill/waybillCargoDetailInfo",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:50:42.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 652,
              "parentId": 628,
              "name": "货检开包详细过程数据",
              "url": "/waybill/waybillCargoCheckOpenInfo",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:48:18.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 631,
              "parentId": 628,
              "name": "货主信用记录",
              "url": "/waybill/creditList",
              "remark": "接口权限",
              "createTime": "2022-09-21T14:28:37.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 651,
              "parentId": 631,
              "name": "根据分数得到信用等级",
              "url": "/waybill/getLevelFlag",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:46:09.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 650,
              "parentId": 631,
              "name": "保存或更新信用等级",
              "url": "/waybill/saveOrUpdateCreditLevel",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:19:59.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 649,
              "parentId": 631,
              "name": "保存或更新信用标签",
              "url": "/waybill/saveOrUpdateCreditFlag",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:18:59.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 648,
              "parentId": 631,
              "name": " 保存或更新货主信用记录",
              "url": "/waybill/saveOrUpdateCredit",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:17:49.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 647,
              "parentId": 631,
              "name": " 保存或更新交货单位等级",
              "url": "/waybill/saveOrUpdateCorpLevel",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:16:45.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 646,
              "parentId": 631,
              "name": "保存或更新加减分记录",
              "url": "/waybill/saveOrUpdateChangeScore",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:15:58.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 645,
              "parentId": 631,
              "name": "删除信用等级",
              "url": "/waybill/removeCreditLevel",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:14:02.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 644,
              "parentId": 631,
              "name": "删除信用标签",
              "url": "/waybill/removeCreditFlag",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:13:07.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 643,
              "parentId": 631,
              "name": "删除货主信用记录",
              "url": "/waybill/removeCredit",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:12:21.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 642,
              "parentId": 631,
              "name": "删除交货单位等级",
              "url": "/waybill/removeCorpLevel",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:11:21.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 641,
              "parentId": 631,
              "name": "删除加分减分记录",
              "url": "/waybill/removeChangeScore",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:08:44.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 640,
              "parentId": 631,
              "name": "查询货主信用记录",
              "url": "/waybill/getCredit",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:05:30.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 639,
              "parentId": 631,
              "name": " 货主信用记录导出",
              "url": "/waybill/exportCreditList",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:04:12.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 638,
              "parentId": 631,
              "name": "信用标签列表",
              "url": "/waybill/creditFlagList",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:02:03.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 637,
              "parentId": 631,
              "name": "货主信用记录的加减分记录",
              "url": "/waybill/changeScoreList",
              "remark": "接口权限",
              "createTime": "2022-09-21T14:59:48.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 634,
              "parentId": 631,
              "name": "货主信用记录列表",
              "url": "/waybill/creditList",
              "remark": "接口权限",
              "createTime": "2022-09-21T14:32:31.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 633,
              "parentId": 631,
              "name": " 交货单位等级列表",
              "url": "/waybill/corpLevelList",
              "remark": "接口权限",
              "createTime": "2022-09-21T14:31:29.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 632,
              "parentId": 631,
              "name": "信用等级列表",
              "url": "/waybill/creditLevelList",
              "remark": "接口权限",
              "createTime": "2022-09-21T14:30:35.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 630,
              "parentId": 628,
              "name": "货物列表信息查询",
              "url": "/waybill/waybillCargoInfo",
              "remark": "接口权限",
              "createTime": "2022-09-21T14:27:12.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 627,
              "parentId": 625,
              "name": "旅检回查",
              "url": "/securityCheck/passageInspect",
              "remark": "菜单权限",
              "createTime": "2022-09-21T13:38:52.000+0800",
              "type": "menu",
              "delFlag": null
            }, {
              "id": 654,
              "parentId": 627,
              "name": "旅客信息查询列表",
              "url": "/scb/passenger/list",
              "remark": "接口权限",
              "createTime": "2022-09-21T15:53:20.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 626,
              "parentId": 625,
              "name": "行检回查",
              "url": "/securityCheck/conductInspect",
              "remark": "菜单权限",
              "createTime": "2022-09-21T13:38:21.000+0800",
              "type": "menu",
              "delFlag": null
            }, {
              "id": 655,
              "parentId": 626,
              "name": "行检列表查询",
              "url": "/scb/luggageInfo/list",
              "remark": "接口权限",
              "createTime": "2022-09-21T16:24:45.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 624,
              "parentId": 621,
              "name": "安检质控",
              "url": "127.0.0.1:7777/startApp",
              "remark": "菜单权限",
              "createTime": "2022-09-21T11:40:31.000+0800",
              "type": "menu",
              "delFlag": null
            }, {"id": 623, "parentId": 621, "name": "统计报表", "url": null, "remark": "菜单权限", "createTime": "2022-09-21T11:29:15.000+0800", "type": "menu", "delFlag": null}, {
              "id": 622,
              "parentId": 621,
              "name": "获取用户信息",
              "url": "/statistics/user/getUserInfo",
              "remark": "接口权限",
              "createTime": "2022-09-21T11:26:19.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 574,
              "parentId": 4,
              "name": "行李总数",
              "url": "/sqc-pax/paxss/getNumAvg",
              "remark": "",
              "createTime": "2020-01-02T17:05:49.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 573,
              "parentId": 4,
              "name": "通道数统计",
              "url": "/sqc-pax/passager/count",
              "remark": "",
              "createTime": "2020-01-02T17:05:09.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 571,
              "parentId": 4,
              "name": "危险品数量",
              "url": "/ali/nums",
              "remark": "",
              "createTime": "2020-01-02T16:58:24.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 570,
              "parentId": 4,
              "name": "平均置信度",
              "url": "/ali/avg-score",
              "remark": "",
              "createTime": "2020-01-02T16:54:53.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 577,
              "parentId": 5,
              "name": "周速率",
              "url": "/sqc-pax/paxss/getRateWeeklyTrend",
              "remark": "",
              "createTime": "2020-01-02T17:09:01.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 576,
              "parentId": 5,
              "name": "周旅客数据",
              "url": "/sqc-pax/paxss/getPassengerFlowWeeklyTrend",
              "remark": "",
              "createTime": "2020-01-02T17:08:25.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 575,
              "parentId": 5,
              "name": "获取安检时间",
              "url": "/sqc-pax/paxss/getCheckTime",
              "remark": "",
              "createTime": "2020-01-02T17:07:15.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 572,
              "parentId": 6,
              "name": "复检图片",
              "url": "/recheckLog/getImageCount",
              "remark": "",
              "createTime": "2020-01-02T17:00:36.000+0800",
              "type": "interface",
              "delFlag": null
            }, {
              "id": 563,
              "parentId": 6,
              "name": "查询登陆记录",
              "url": "sloLog/getTodayOnEmp",
              "remark": "",
              "createTime": "2019-12-16T11:05:18.000+0800",
              "type": "interface",
              "delFlag": null
            }], "picture":
            "http://192.168.17.50:32681/xingyi-img/20220902/1662109549318.jpg", "token":
            "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoi57O757uf566h55CG5ZGYIiwiZW1wTnVtYmVyIjoiMjUyMDU1OSIsInVzZXJOYW1lIjoiMjUyMDU1OSIsInVzZXJJZCI6NjQ2LCJpYXQiOjE2NjY2NjY0Njg2NTAsInN0YWZmSWQiOiIyNTIwNTU5In0.QkkziEA3_7iy3hac6q2zQo9549O8Ojz8AlKLmHhQFOM"
      }
}